##
## Copyright Elasticsearch B.V. and contributors
## SPDX-License-Identifier: Apache-2.0
##
services:
  phoenix:
    image: arizephoenix/phoenix:version-10.2.2
    container_name: phoenix
    ports:
      - 6006:6006
      - 4317:4317
    environment:
      - PHOENIX_ENABLE_AUTH=false
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; exit() if requests.get(\"http://localhost:6006/healthz\").status_code == 200 else exit(1)",
        ]
      start_period: 10s
      interval: 1s
      timeout: 10s
      retries: 120

  test:
    container_name: test
    build:
      context: .
      target: test
    command: -m vcr --vcr-record=none

  integration-test: &default-service
    container_name: integration-test
    build:
      context: .
      target: test
    command: -m integration
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
      - "localhost:${HOST_IP:-host-gateway}"
    volumes:
      - ../.env:/.env

  eval:
    build:
      context: .
      target: eval
    container_name: eval
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
      - "localhost:${HOST_IP:-host-gateway}"
    entrypoint: [ "dotenv",  "-f", "../.env", "run", "--no-override", "--" ]
    command: [ "python3", "run_evals.py" ]
    volumes:
      - ../.env:/.env

  main:
    container_name: main
    build:
      target: main
    environment:
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
      - "localhost:${HOST_IP:-host-gateway}"
    volumes:
      - ../.env:/.env
