include_fragments = false
exclude_all_private = true

accept = [
    "200..=299",
    # Consider a 403 to be success. Cloudflare-protected sites, like
    # https://platform.openai.com, return a 403 to lychee.
    "403"
]

exclude = [
    # OPENAI_BASE_URL is 404
    "https://api.openai.com/v1"
]

# better to be safe and avoid failures
max_retries = 6
