##
## Copyright Elasticsearch B.V. and contributors
## SPDX-License-Identifier: Apache-2.0
##

services:
  test: &default-service
    container_name: test
    build:
      context: .
      target: test
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
      - "localhost:${HOST_IP:-host-gateway}"
    volumes:
      - ../.env:/.env

  main:
    <<: *default-service
    container_name: main
    build:
      target: main
