##
## Copyright Elasticsearch B.V. and contributors
## SPDX-License-Identifier: Apache-2.0
##

services:
  cli:
    container_name: cli
    build:
      context: .
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
      - "localhost:${HOST_IP:-host-gateway}"
    volumes:  # Add volumes for our environment variables and mitmproxy's certs
      - ./.env:/.env
      - ./.mitmproxy/mitmproxy-ca-cert.pem:/.mitmproxy/mitmproxy-ca-cert.pem
