##
## Copyright Elasticsearch B.V. and contributors
## SPDX-License-Identifier: Apache-2.0
##
services:
  test:
    container_name: test
    build:
      context: .
      target: test
    command: -m "not integration or eval" --vcr-record=none

  integration-test: &default-service
    container_name: integration-test
    build:
      context: .
      target: test
    command: -m integration
    extra_hosts:  # send localhost traffic to the docker host, e.g. your laptop
      - "localhost:${HOST_IP:-host-gateway}"
    volumes:
      - ../.env:/.env

  eval-test:
    <<: *default-service
    container_name: eval-test
    build:
      context: .
      target: test
    entrypoint: [ "dotenv",  "-f", "../.env", "run", "--no-override", "--" ]
    command: [ "sh", "-c", "opentelemetry-instrument pytest -s -m eval" ]

  main:
    <<: *default-service
    container_name: main
    build:
      target: main
